const userActionTypes = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGIN_BY_FACEBOOK: 'LOGIN_BY_FACEBOOK',
    USER_UPDATE: 'USER_UPDATE',
    SEARCH_HISTORY_UPDATE: 'SEARCH_HISTORY_UPDATE',
    PUSH_TOKEN_UPDATE: 'PUSH_TOKEN_UPDATE',
    UPDATE_REQUEST_COOKIE: 'UPDATE_REQUEST_COOKIE',
    USER_FAVORITE_IDS_UPDATE: 'USER_FAVORITE_IDS_UPDATE',
    APP_ACTIVE: 'APP_ACTIVE',
};

export default userActionTypes;