const settingActionTypes = {
    LANGUAGE_UPDATE: 'LANGUAGE_UPDATE',
    DISPLAY_CURRENCY_UPDATE: 'DISPLAY_CURRENCY_UPDATE',
    SEARCH_COUNTRY_UPDATE: 'SEARCH_COUNTRY_UPDATE',
    DEVICE_COUNTRY_UPDATE: 'DEVICE_COUNTRY_UPDATE',
    IS_OPEN_DEBUG_MODE: 'IS_OPEN_DEBUG_MODE'
};

export default  settingActionTypes;