const walletActionTypes = {
    WITHDRAW_ACCOUNT_UPDATE: 'WITHDRAW_ACCOUNT_UPDATE',
    PENDING_WITHDRAW_ACCOUNT_UPDATE: 'PENDING_WITHDRAW_ACCOUNT_UPDATE',
    BALANCE_UPDATE: 'BALANCE_UPDATE',

    PAY_CREDIT_CARD_UPDATE: 'PAY_CREDIT_CARD_UPDATE',
};

export default  walletActionTypes;