const metaActionTypes = {
    META_CATEGORY_UPDATE: 'META_CATEGORY_UPDATE',
    META_ALL_AREAS_UPDATE: 'META_ALL_AREAS_UPDATE',
    META_VOUCHER_CLUB_RELOAD_LIST_PRODUCT: 'META_VOUCHER_CLUB_RELOAD_LIST_PRODUCT'
};

export default  metaActionTypes;