# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
    pod 'RSKImageCropper'
    pod 'QBImagePickerController'
    pod 'HockeySDK'
    pod 'GooglePlaces'
    pod 'GoogleMaps'
    pod 'GooglePlacePicker'
    pod 'ZXingObjC'
end


target 'FuldaMallProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FuldaMallProject

  # target 'FuldaMallProject-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end
  common_pods

  target 'FuldaMallProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'FuldaMallProjectStage' do
    common_pods
end

target 'FuldaMallProjectProduction' do
    common_pods
end

target 'FuldaMallProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FuldaMallProject-tvOS
  
  target 'FuldaMallProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
