const orderActionTypes = {
    DELIVER_ADDRESS_UPDATE: 'DELIVER_ADDRESS_UPDATE',
    DEFAULT_DELIVER_ADDRESS_UPDATE: 'DEFAULT_DELIVER_ADDRESS_UPDATE',
    ADD_TO_SHOPPING_CART: 'ADD_TO_SHOPPING_CART',
    REMOVE_FROM_SHOPPING_CART: 'REMOVE_FROM_SHOPPING_CART',
    UPDATE_SHOPPING_CART: 'UPDATE_SHOPPING_CART',
    UPDATE_SHOPPING_CART_SHOP_REMARK: 'UPDATE_SHOPPING_CART_SHOP_REMARK',
    UPDATE_SHOPPING_CART_SHOP_SHIPPING: 'UPDATE_SHOPPING_CART_SHOP_SHIPPING',
    UPDATE_PENDING_DELIVER_ADDRESS_ID: "UPDATE_PENDING_DELIVER_ADDRESS_ID"
};

export default  orderActionTypes;